app = "lanjii-backend"

[build]
  # Fly will build using the Dockerfile at project root

[env]
  JAVA_TOOL_OPTIONS = "-Xmx300m"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls","http"]
